[package]
name = "aei-framework"
version = "0.1.0"
edition = "2021"
description = "Core of the AEI Framework for dynamic neural networks."
license = "MPL-2.0"
publish = false

[workspace]
members = [
    "crates/core",
    "crates/memory",
    "crates/runtime",
    "crates/modules",
    "crates/utils",
]
resolver = "2"

[dependencies]
uuid = { version = "1", features = ["v4"] }
