[package]
name = "aei-framework"
version = "0.1.0"
edition = "2021"
description = "Root crate for the Autonomous & Evolutive Intelligence Framework workspace."
license = "MPL-2.0"
publish = false

[workspace]
members = [
    "crates/core",
    "crates/memory",
    "crates/runtime",
    "crates/modules",
    "crates/utils",
]
resolver = "2"
